# Generated by Django 6.0.5 on 2026-05-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='About BoosterNotes', max_length=200, verbose_name='Heading')),
                ('text1', models.TextField(verbose_name='First Paragraph')),
                ('text2', models.TextField(blank=True, null=True, verbose_name='Second Paragraph (optional)')),
                ('pdf_count', models.CharField(default='343+', max_length=20, verbose_name='PDF Resources Count')),
                ('books_count', models.CharField(default='500+', max_length=20, verbose_name='Books Count')),
                ('users_count', models.CharField(default='2456+', max_length=20, verbose_name='Users Count')),
                ('categories_count', models.CharField(default='10+', max_length=20, verbose_name='Exam Categories Count')),
                ('feature1_icon', models.CharField(default='⚡', max_length=20, verbose_name='Feature 1 Icon')),
                ('feature1_title', models.CharField(default='Fast Download', max_length=100, verbose_name='Feature 1 Title')),
                ('feature1_desc', models.TextField(default='Get instant access to PDF study material after purchase.', verbose_name='Feature 1 Description')),
                ('feature2_icon', models.CharField(default='🎯', max_length=20, verbose_name='Feature 2 Icon')),
                ('feature2_title', models.CharField(default='Exam Targeted', max_length=100, verbose_name='Feature 2 Title')),
                ('feature2_desc', models.TextField(default='Curated content for NEET, JEE, UPSC, SSC, and more.', verbose_name='Feature 2 Description')),
                ('feature3_icon', models.CharField(default='💬', max_length=20, verbose_name='Feature 3 Icon')),
                ('feature3_title', models.CharField(default='Support', max_length=100, verbose_name='Feature 3 Title')),
                ('feature3_desc', models.TextField(default='Support available on WhatsApp during working hours.', verbose_name='Feature 3 Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'About Setting',
                'verbose_name_plural': 'About Settings',
            },
        ),
        migrations.CreateModel(
            name='BannerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_banner_image', models.ImageField(blank=True, null=True, upload_to='banners/desktop/', verbose_name='Desktop Banner Image')),
                ('mobile_banner_image', models.ImageField(blank=True, null=True, upload_to='banners/mobile/', verbose_name='Mobile Banner Image')),
                ('desktop_banner_gradient', models.CharField(default='linear-gradient(135deg,#1a3a8f,#0d2060)', max_length=100, verbose_name='Desktop Banner Gradient (fallback)')),
                ('mobile_banner_gradient', models.CharField(default='linear-gradient(135deg,#0a4a2a,#1a3a8f)', max_length=100, verbose_name='Mobile Banner Gradient (fallback)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Banner Setting',
                'verbose_name_plural': 'Banner Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='BoosterNotes', max_length=100, verbose_name='Brand Name')),
                ('tagline', models.CharField(default='Smart Notes. Smart Rank.', max_length=200, verbose_name='Tagline')),
                ('description', models.TextField(default='Reliable study resources for competitive exams.', verbose_name='Description')),
                ('quick_links_title', models.CharField(default='Quick Links', max_length=100, verbose_name='Quick Links Title')),
                ('support_title', models.CharField(default='Support', max_length=100, verbose_name='Support Title')),
                ('contact_title', models.CharField(default='Contact', max_length=100, verbose_name='Contact Title')),
                ('whatsapp_contact', models.CharField(default='WhatsApp: 6350331916', max_length=50, verbose_name='WhatsApp Contact')),
                ('hours_contact', models.CharField(default='10 AM - 7 PM', max_length=50, verbose_name='Hours')),
                ('copyright_text', models.CharField(default='© 2026 BoosterNotes. All rights reserved.', max_length=200, verbose_name='Copyright Text')),
                ('social_facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook URL')),
                ('social_linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn URL')),
                ('social_instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram URL')),
                ('social_youtube', models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Footer Setting',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='NavbarSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='BoosterNotes', max_length=100, verbose_name='Brand Name')),
                ('tagline', models.CharField(default='Smart Notes. Smart Rank', max_length=100, verbose_name='Tagline')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo Image')),
                ('search_placeholder', models.CharField(default='Search pdf courses, exams...', max_length=200, verbose_name='Search Placeholder')),
                ('whatsapp_number', models.CharField(default='6350331916', max_length=20, verbose_name='WhatsApp Number')),
                ('whatsapp_hours', models.CharField(default='10 AM to 7 PM', max_length=50, verbose_name='WhatsApp Hours')),
                ('coupon_text', models.CharField(default='🎟️ Apply Coupon', max_length=100, verbose_name='Coupon Button Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Navbar Setting',
                'verbose_name_plural': 'Navbar Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Setting Key')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Setting Value')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='StatsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20, verbose_name='Icon (emoji)')),
                ('value', models.CharField(max_length=50, verbose_name='Value (e.g., 343, 500+)')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Note/Subtitle')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Stats Setting',
                'verbose_name_plural': 'Stats Settings',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
