# Generated by Django 6.0.5 on 2026-05-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_aboutsetting_bannersetting_footersetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='Favicon (16x16 or 32x32 PNG)'),
        ),
    ]
