# Generated by Django 6.0.5 on 2026-05-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_bannerslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerDesktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/desktop/', verbose_name='Desktop Banner Image')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Desktop Banner',
                'verbose_name_plural': 'Desktop Banners',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BannerMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/mobile/', verbose_name='Mobile Banner Image')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mobile Banner',
                'verbose_name_plural': 'Mobile Banners',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='BannerSlide',
        ),
        migrations.RemoveField(
            model_name='bannersetting',
            name='desktop_banner_gradient',
        ),
        migrations.RemoveField(
            model_name='bannersetting',
            name='mobile_banner_gradient',
        ),
    ]
