# Generated by Django 6.0.5 on 2026-05-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_bannerdesktop_bannermobile_delete_bannerslide_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerDesktop',
        ),
        migrations.DeleteModel(
            name='BannerMobile',
        ),
        migrations.RemoveField(
            model_name='navbarsetting',
            name='favicon',
        ),
        migrations.AddField(
            model_name='bannersetting',
            name='desktop_banner_gradient',
            field=models.CharField(default='linear-gradient(135deg,#1a3a8f,#0d2060)', max_length=100, verbose_name='Desktop Banner Gradient (fallback)'),
        ),
        migrations.AddField(
            model_name='bannersetting',
            name='mobile_banner_gradient',
            field=models.CharField(default='linear-gradient(135deg,#0a4a2a,#1a3a8f)', max_length=100, verbose_name='Mobile Banner Gradient (fallback)'),
        ),
    ]
