# Generated by Django 6.0.5 on 2026-05-31 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_bannerdesktop_delete_bannermobile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannersetting',
            options={'ordering': ['banner_type', 'order'], 'verbose_name': 'Banner Setting', 'verbose_name_plural': 'Banner Settings'},
        ),
        migrations.RemoveField(
            model_name='bannersetting',
            name='desktop_banner_gradient',
        ),
        migrations.RemoveField(
            model_name='bannersetting',
            name='desktop_banner_image',
        ),
        migrations.RemoveField(
            model_name='bannersetting',
            name='mobile_banner_gradient',
        ),
        migrations.RemoveField(
            model_name='bannersetting',
            name='mobile_banner_image',
        ),
        migrations.AddField(
            model_name='bannersetting',
            name='banner_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], default='desktop', max_length=10, verbose_name='Banner Type'),
        ),
        migrations.AddField(
            model_name='bannersetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='bannersetting',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='bannersetting',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
