# Generated by Django 6.0.5 on 2026-05-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_bannersetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statssetting',
            name='icon_color',
            field=models.CharField(default='#1a3a8f', max_length=20, verbose_name='Icon Color (hex code)'),
        ),
        migrations.AlterField(
            model_name='statssetting',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='Icon (Font Awesome class)'),
        ),
    ]
