# Generated by Django 6.0.5 on 2026-05-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_statssetting_icon_color_alter_statssetting_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsetting',
            options={'ordering': ['id'], 'verbose_name': 'About Setting', 'verbose_name_plural': 'About Settings'},
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='feature1_icon_color',
            field=models.CharField(default='#1a3a8f', max_length=20, verbose_name='Feature 1 Icon Color'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='feature2_icon_color',
            field=models.CharField(default='#28a745', max_length=20, verbose_name='Feature 2 Icon Color'),
        ),
        migrations.AddField(
            model_name='aboutsetting',
            name='feature3_icon_color',
            field=models.CharField(default='#ffc107', max_length=20, verbose_name='Feature 3 Icon Color'),
        ),
        migrations.AlterField(
            model_name='aboutsetting',
            name='feature1_icon',
            field=models.CharField(default='fa-solid fa-bolt', max_length=50, verbose_name='Feature 1 Icon (Font Awesome class)'),
        ),
        migrations.AlterField(
            model_name='aboutsetting',
            name='feature2_icon',
            field=models.CharField(default='fa-solid fa-bullseye', max_length=50, verbose_name='Feature 2 Icon (Font Awesome class)'),
        ),
        migrations.AlterField(
            model_name='aboutsetting',
            name='feature3_icon',
            field=models.CharField(default='fa-solid fa-comments', max_length=50, verbose_name='Feature 3 Icon (Font Awesome class)'),
        ),
    ]
