# Generated by Django 6.0.5 on 2026-05-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_aboutsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footersetting',
            options={'ordering': ['id'], 'verbose_name': 'Footer Setting', 'verbose_name_plural': 'Footer Settings'},
        ),
        migrations.AddField(
            model_name='footersetting',
            name='social_facebook_color',
            field=models.CharField(default='#1877f2', max_length=20, verbose_name='Facebook Icon Color'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='social_instagram_color',
            field=models.CharField(default='#e4405f', max_length=20, verbose_name='Instagram Icon Color'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='social_linkedin_color',
            field=models.CharField(default='#0a66c2', max_length=20, verbose_name='LinkedIn Icon Color'),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='social_youtube_color',
            field=models.CharField(default='#ff0000', max_length=20, verbose_name='YouTube Icon Color'),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='social_instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='social_linkedin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='social_youtube',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='YouTube URL'),
        ),
    ]
