# Generated by Django 6.0.5 on 2026-05-31 13:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_footersetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELibraryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Original Price')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Price')),
                ('thumbnail', models.ImageField(upload_to='elibrary/thumbnails/', verbose_name='Thumbnail Image')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-Library Item',
                'verbose_name_plural': 'E-Library Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ELibraryPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_name', models.CharField(max_length=200, verbose_name='PDF Name')),
                ('pdf_file', models.FileField(upload_to='elibrary/pdfs/', verbose_name='PDF File (will be saved to Dropbox)')),
                ('dropbox_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dropbox Path')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='myapp.elibrarymodel', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'E-Library PDF',
                'verbose_name_plural': 'E-Library PDFs',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
