# Generated by Django 6.0.5 on 2026-05-31 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_elibrarymodel_elibrarypdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elibrarymodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elibrary_courses', to='myapp.category', verbose_name='Category'),
        ),
    ]
