# Generated by Django 6.0.5 on 2026-06-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_navbarsetting_favicon_navbarsetting_favicon_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarsetting',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='navbarsetting',
            name='favicon_url',
        ),
        migrations.RemoveField(
            model_name='navbarsetting',
            name='logo_url',
        ),
    ]
