# Generated by Django 6.0.5 on 2026-06-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_navbarsetting_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='Favicon'),
        ),
    ]
