# Generated by Django 6.0.5 on 2026-06-01 12:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_navbarsetting_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Book Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Original Price')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sale Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hard Book',
                'verbose_name_plural': 'Hard Books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HardBookImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='hardbooks/images/', verbose_name='Book Image')),
                ('dropbox_path', models.CharField(blank=True, max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.hardbook', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Hard Book Image',
                'verbose_name_plural': 'Hard Book Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
